version: 0.2
phases:
  install:
    commands:
      - npm install -g aws-cdk
      - cdk --version
      - ls -al
      - pip install --upgrade pip
  build:
    commands:
      - pip install -r requirements.txt
      - cdk synth -o dist
artifacts:
  base-directory: dist
  files: '**/*'
