version: 0.2
phases:
  install:
    commands:
      - npm install -g aws-cdk
      - cdk --version
      - ls -al
      - pip install --upgrade pip
  pre_build:
    commands:
      - echo $LAMBDA_CODE_BUCKET
      - zip -j $SOURCE_BUNDLE_NAME $CODE_PATH/$LAMBDA_FUNCTION_FILENAME_A
      - zip -j $SOURCE_BUNDLE_NAME $CODE_PATH/$LAMBDA_FUNCTION_FILENAME_B
      - zipinfo $SOURCE_BUNDLE_NAME
      - aws s3 cp $SOURCE_BUNDLE_NAME s3://$LAMBDA_CODE_BUCKET
  build:
    commands:
      - pip install -r requirements.txt
      - cdk synth -o dist
artifacts:
  base-directory: dist1
  files: '**/*'
